name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install packages
      run: sudo apt install -y opam zlib1g-dev pkg-config libgmp-dev z3 device-tree-compiler
    - name: Check out repository code
      uses: actions/checkout@HEAD
      with:
        submodules: recursive
    - name: Ensure pre-commit checks pass
      run: pip install pre-commit && pre-commit run --all-files --show-diff-on-failure --color=always
    - name: Init opam
      run: opam init --disable-sandboxing -y
    - name: Install sail
      run: opam install -y sail
    - name: Download RISC-V toolchain (32-bit)
      run: wget -c https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2024.04.12/riscv32-glibc-ubuntu-22.04-gcc-nightly-2024.04.12-nightly.tar.gz
    - name: Install RISC-V toolchain (32-bit)
      run: sudo tar xvfz riscv32-glibc-ubuntu-22.04-gcc-nightly-2024.04.12-nightly.tar.gz --directory /opt
    - name: Download RISC-V toolchain (64-bit)
      run: wget -c https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2024.04.12/riscv64-glibc-ubuntu-22.04-gcc-nightly-2024.04.12-nightly.tar.gz
    - name: Install RISC-V toolchain (32-bit)
      run: sudo tar xvfz riscv64-glibc-ubuntu-22.04-gcc-nightly-2024.04.12-nightly.tar.gz --directory /opt
    - name: Build RISC-V testsuite
      run: |
        cd TEST_DIR_ROOT/riscv_tests.git ; \
        echo ${PWD} ; ls ; \
        autoconf ;  \
        ./configure --prefix=${PWD}/target ; \
        make isa ;
    - name: Build and test simulators
      run: eval $(opam env) && test/run_tests.sh
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tests.xml
        path: test/tests.xml
    - name: Upload event payload
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: event.json
        path: ${{ github.event_path }}
